### ISSUE TITLE
File folds.csv does not exist

### ISSUE THREAD

**Issue by wangzt2012** [tatigabru/kaggle-rsna#3]
https://github.com/tatigabru/kaggle-rsna/blob/c16faf6b469f88f0af439fae0223141779d8321e/src/datasets/detection_dataset.py#L48

I run the code, and encountered "FileNotFoundError: [Errno 2] File dataset/folds.csv does not exist: 'dataset/folds.csv' "

**Comment by sharmapratik88** [comment]
Should be this one: https://github.com/tatigabru/kaggle-rsna/tree/69aa059170d3a30ee91b6d68f025523000d77ccc/src/folds

You can change the directory just for the folds file.

```samples = sample.merge(pd.read_csv(os.path.join("../../folds", "folds.csv")), on="patientId", how="left")```

**Comment by alxndrkalinin** [comment]
Yes, that's the correct file path
